### ISSUE TITLE
eapictl fails because of paramiko.ssh_exception.BadAuthenticationType

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/eapictl#1]
<pre>
$ eapictl status spine1
Traceback (most recent call last):
  File "/usr/local/bin/eapictl", line 9, in <module>
    load_entry_point('eapictl==0.1.0', 'console_scripts', 'eapictl')()
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 462, in main
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 139, in __init__
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 99, in connect_ssh
  File "build/bdist.macosx-10.10-intel/egg/paramiko/client.py", line 307, in connect
  File "build/bdist.macosx-10.10-intel/egg/paramiko/client.py", line 519, in _auth
paramiko.ssh_exception.BadAuthenticationType: ('Bad authentication type', [u'publickey', u'keyboard-interactive']) (allowed_types=[u'publickey', u'keyboard-interactive'])
</pre>

**Comment by advornic** [comment]
<pre>
$ eapictl status spine1 --username admin --password admin
Traceback (most recent call last):
  File "/usr/local/bin/eapictl", line 9, in <module>
    load_entry_point('eapictl==0.1.0', 'console_scripts', 'eapictl')()
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 485, in main
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 203, in status
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 173, in send_enable
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 169, in sendall
  File "build/bdist.macosx-10.10-intel/egg/eapictl/app.py", line 162, in send
IOError: Socket timeout for host spine1
</pre>

But this works:

<pre>
$ ssh admin@spine1
Password: 
Last login: Tue Apr 14 18:06:55 2015 from 172.16.130.1
veos-dc1-pod1-spine1>
</pre>

**Comment by sugetha24** [comment]
I am having the same issue as well. I could ping the switch and ssh into it. I have no password set.

**Comment by Josen15** [comment]
@sugetha24 I ping the switch  ,but it says the same issue .Can you help me ?

**Comment by jerearista** [comment]
@Josen15 are you also attempting to connect with no password?  If so, can you try with a user that does have a password?

**Comment by jerearista** [comment]
@sugetha24 Paramiko does not support keyboard-interactive login without a password.
https://github.com/paramiko/paramiko/blob/6830a905cc38261d9e4054b87294959dac6a1b5c/paramiko/client.py#L489-L501
https://github.com/paramiko/paramiko/blob/6830a905cc38261d9e4054b87294959dac6a1b5c/paramiko/client.py#L607-L612
